export const INPUT_CHANGE = 'INPUT_CHANGE';
export const ADD_SUM = 'ADD_SUM';
export const SET_WIDGET_DATA = 'SET_WIDGET_DATA';
export const ON_DATA_TABLE_SORT = 'ON_DATA_TABLE_SORT';
export const TOGGLE_IS_FETHING = 'TOGGLE_IS_FETHING';
