export const INPUT_CHANGE = 'INPUT_CHANGE';
export const ADD_SUM = 'ADD_SUM';
export const GET_WIDGET_DATA = 'GET_WIDGET_DATA';
export const ON_DATA_TABLE_SORT = 'ON_DATA_TABLE_SORT';
export const GET_WIDGET_DATA_LOADING = 'GET_WIDGET_DATA_LOADING';
export const GET_WIDGET_DATA_SUCCESS = 'GET_WIDGET_DATA_SUCCESS';
export const GET_WIDGET_DATA_ERROR = 'GET_WIDGET_DATA_ERROR';
